// Seed officiel des règles EAP — correspond 1:1 à la spec
// "LEAD SCORING EAP — GUIDE OPÉRATIONNEL" (340 pts max).
//
// is_system: true → toutes les règles seed (non supprimables, points éditables).

import type { EapScoringRule } from './schemas/eap-scoring-rule.schema'

type SeedRule = Omit<EapScoringRule, never>

export const EAP_SCORING_SEED: SeedRule[] = [
  // ── Q15 Pack choisi ──────────────────────────────────────────────────────
  { key: 'pack_e', category: 'pack', label: 'Pack E — Plus de 10M FCFA',  description: 'Tier le plus élevé', match_type: 'pack_tier', match_config: { tier: 'E' }, points: 100, priority: 50, display_order: 1, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'pack_d', category: 'pack', label: 'Pack D — 3M à 10M FCFA',     description: '', match_type: 'pack_tier', match_config: { tier: 'D' }, points: 80,  priority: 40, display_order: 2, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'pack_c', category: 'pack', label: 'Pack C — 1M à 3M FCFA',      description: '', match_type: 'pack_tier', match_config: { tier: 'C' }, points: 60,  priority: 30, display_order: 3, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'pack_b', category: 'pack', label: 'Pack B — 200K à 1M FCFA',    description: '', match_type: 'pack_tier', match_config: { tier: 'B' }, points: 30,  priority: 20, display_order: 4, is_active: true, is_system: true, disqualification_reason: '' },

  // ── Q16 Acompte mobilisable (amount_range, single-pick par priorité) ─────
  { key: 'acompte_above_500k', category: 'acompte', label: 'Acompte > 500 000 FCFA',   description: '', match_type: 'amount_range', match_config: { field: 'q16_montant_acompte', min_amount: 500001, max_amount: null }, points: 80, priority: 40, display_order: 1, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'acompte_200k_500k',  category: 'acompte', label: 'Acompte 200K à 500K FCFA', description: '', match_type: 'amount_range', match_config: { field: 'q16_montant_acompte', min_amount: 200000, max_amount: 500000 }, points: 60, priority: 30, display_order: 2, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'acompte_100k_200k',  category: 'acompte', label: 'Acompte 100K à 200K FCFA', description: '', match_type: 'amount_range', match_config: { field: 'q16_montant_acompte', min_amount: 100000, max_amount: 199999 }, points: 30, priority: 20, display_order: 3, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'acompte_below_100k', category: 'acompte', label: 'Acompte < 100K FCFA',      description: '', match_type: 'amount_range', match_config: { field: 'q16_montant_acompte', min_amount: 0, max_amount: 99999 }, points: 10, priority: 10, display_order: 4, is_active: true, is_system: true, disqualification_reason: '' },

  // ── Q14 Objectif gain (regex prioritaire, fallback amount_range) ─────────
  { key: 'objectif_10m_plus', category: 'objectif_gain', label: 'Objectif > 10M FCFA',   description: '', match_type: 'regex', match_config: { field: 'q14_objectif_gain', pattern: '(\\+|plus de)?\\s*10\\s*m|10\\s*000\\s*000', case_insensitive: true }, points: 30, priority: 60, display_order: 1, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'objectif_5m_10m',   category: 'objectif_gain', label: 'Objectif 5M à 10M',     description: '', match_type: 'regex', match_config: { field: 'q14_objectif_gain', pattern: '(\\+|plus de)?\\s*5\\s*m|5\\s*000\\s*000', case_insensitive: true }, points: 25, priority: 50, display_order: 2, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'objectif_1m_5m',    category: 'objectif_gain', label: 'Objectif 1M à 5M',      description: '', match_type: 'regex', match_config: { field: 'q14_objectif_gain', pattern: '1\\s*m.*5\\s*m|1[\\s-]*[à\\-][\\s]*5\\s*m', case_insensitive: true }, points: 20, priority: 40, display_order: 3, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'objectif_500k_1m',  category: 'objectif_gain', label: 'Objectif 500K à 1M',    description: '', match_type: 'regex', match_config: { field: 'q14_objectif_gain', pattern: '500\\s*k.*1\\s*m|500[\\s-]*[à\\-][\\s]*1\\s*m', case_insensitive: true }, points: 15, priority: 30, display_order: 4, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'objectif_300k_500k', category: 'objectif_gain', label: 'Objectif 300K à 500K', description: '', match_type: 'regex', match_config: { field: 'q14_objectif_gain', pattern: '300\\s*k.*500\\s*k', case_insensitive: true }, points: 10, priority: 20, display_order: 5, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'objectif_0_300k',   category: 'objectif_gain', label: 'Objectif 0 à 300K',     description: '', match_type: 'regex', match_config: { field: 'q14_objectif_gain', pattern: '0.*300\\s*k', case_insensitive: true }, points: 5,  priority: 10, display_order: 6, is_active: true, is_system: true, disqualification_reason: '' },

  // ── Q12 Connaissance Myril ───────────────────────────────────────────────
  { key: 'myril_3_ans_plus', category: 'connaissance_myril', label: 'Connaît Myril depuis 3 ans ou plus',  description: '', match_type: 'regex', match_config: { field: 'q12_connaissance_myril', pattern: '\\+\\s*3\\s*ans|plus de 3 ans|3\\s*ans? et plus', case_insensitive: true }, points: 25, priority: 60, display_order: 1, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'myril_2_ans',      category: 'connaissance_myril', label: 'Connaît Myril depuis 2 ans',           description: '', match_type: 'regex', match_config: { field: 'q12_connaissance_myril', pattern: '\\+\\s*2\\s*ans|plus de 2 ans|2\\s*ans', case_insensitive: true }, points: 20, priority: 50, display_order: 2, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'myril_1_an',       category: 'connaissance_myril', label: 'Connaît Myril depuis 1 an',            description: '', match_type: 'regex', match_config: { field: 'q12_connaissance_myril', pattern: '\\+\\s*1\\s*an|plus d[\'’]un an|1\\s*an\\b', case_insensitive: true }, points: 15, priority: 40, display_order: 3, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'myril_3_12_mois',  category: 'connaissance_myril', label: 'Connaît Myril depuis 3 à 12 mois',     description: '', match_type: 'regex', match_config: { field: 'q12_connaissance_myril', pattern: '3\\s*[à\\-]\\s*12\\s*mois|entre 3 et 12 mois', case_insensitive: true }, points: 10, priority: 30, display_order: 4, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'myril_1_3_mois',   category: 'connaissance_myril', label: 'Connaît Myril depuis 1 à 3 mois',      description: '', match_type: 'regex', match_config: { field: 'q12_connaissance_myril', pattern: '1\\s*[à\\-]\\s*3\\s*mois|entre 1 et 3 mois', case_insensitive: true }, points: 7,  priority: 20, display_order: 5, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'myril_nouveau',    category: 'connaissance_myril', label: 'Vient de découvrir Myril',             description: '', match_type: 'regex', match_config: { field: 'q12_connaissance_myril', pattern: 'viens de.*d[ée]couvrir|d[ée]couverte|nouveau', case_insensitive: true }, points: 3,  priority: 10, display_order: 6, is_active: true, is_system: true, disqualification_reason: '' },

  // ── Q10 Expérience e-commerce ────────────────────────────────────────────
  { key: 'ecom_vend_deja', category: 'experience_ecom', label: 'Vend déjà en e-commerce',     description: '', match_type: 'regex', match_config: { field: 'q10_experience_ecom', pattern: 'vends d[ée]j[àa]|d[ée]j[àa].*vends?|je vends', case_insensitive: true }, points: 20, priority: 30, display_order: 1, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'ecom_essaye',    category: 'experience_ecom', label: 'A essayé l\'e-commerce',       description: '', match_type: 'regex', match_config: { field: 'q10_experience_ecom', pattern: 'essay[ée]', case_insensitive: true }, points: 15, priority: 20, display_order: 2, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'ecom_jamais',    category: 'experience_ecom', label: 'N\'a jamais touché l\'e-commerce', description: '', match_type: 'regex', match_config: { field: 'q10_experience_ecom', pattern: 'jamais', case_insensitive: true }, points: 5,  priority: 10, display_order: 3, is_active: true, is_system: true, disqualification_reason: '' },

  // ── Q11 Investi en formation ─────────────────────────────────────────────
  { key: 'invest_oui', category: 'invest_formation', label: 'A déjà investi en formation',         description: '', match_type: 'regex', match_config: { field: 'q11_invest_formation', pattern: '^oui\\b', case_insensitive: true }, points: 15, priority: 20, display_order: 1, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'invest_non', category: 'invest_formation', label: 'N\'a jamais investi en formation',    description: '', match_type: 'regex', match_config: { field: 'q11_invest_formation', pattern: '^non\\b', case_insensitive: true }, points: 3,  priority: 10, display_order: 2, is_active: true, is_system: true, disqualification_reason: '' },

  // ── Q9 Situation professionnelle ─────────────────────────────────────────
  { key: 'situation_entrepreneur', category: 'situation_pro', label: 'Entrepreneur', description: '', match_type: 'regex', match_config: { field: 'q9_situation_pro', pattern: 'entrepreneur', case_insensitive: true }, points: 20, priority: 60, display_order: 1, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'situation_freelance',    category: 'situation_pro', label: 'Freelance',     description: '', match_type: 'regex', match_config: { field: 'q9_situation_pro', pattern: 'freelance', case_insensitive: true }, points: 15, priority: 50, display_order: 2, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'situation_salarie',      category: 'situation_pro', label: 'Salarié',       description: '', match_type: 'regex', match_config: { field: 'q9_situation_pro', pattern: 'salari[ée]', case_insensitive: true }, points: 12, priority: 40, display_order: 3, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'situation_artisan',      category: 'situation_pro', label: 'Artisan',       description: '', match_type: 'regex', match_config: { field: 'q9_situation_pro', pattern: 'artisan', case_insensitive: true }, points: 10, priority: 30, display_order: 4, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'situation_etudiant',     category: 'situation_pro', label: 'Étudiant',      description: '', match_type: 'regex', match_config: { field: 'q9_situation_pro', pattern: '[ée]tudiant', case_insensitive: true }, points: 7,  priority: 20, display_order: 5, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'situation_chomeur',      category: 'situation_pro', label: 'Chômeur',       description: '', match_type: 'regex', match_config: { field: 'q9_situation_pro', pattern: 'ch[ôo]meur|sans emploi', case_insensitive: true }, points: 3,  priority: 10, display_order: 6, is_active: true, is_system: true, disqualification_reason: '' },

  // ── Bonus auto ───────────────────────────────────────────────────────────
  { key: 'bonus_diaspora',     category: 'bonus', label: 'Bonus diaspora',              description: 'Pays dans la liste diaspora cible', match_type: 'contains_any', match_config: { field: 'pays', values: ['france','canada','usa','états-unis','etats-unis','united states','belgique','suisse','allemagne','italie','espagne','portugal','pays-bas','royaume-uni','angleterre','uk','royaume uni','irlande','luxembourg','autriche','suède','norvège','danemark','finlande'] }, points: 15, priority: 30, display_order: 1, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'bonus_motivation',   category: 'bonus', label: 'Bonus motivation rédigée',    description: 'Motivation ≥ 80 caractères avec ponctuation', match_type: 'text_length', match_config: { field: 'motivation', min_length: 80, requires_punctuation: true }, points: 10, priority: 20, display_order: 2, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'bonus_retour_eap',   category: 'bonus', label: 'Bonus ancien étudiant EAP',   description: 'Mention de retour / ancien étudiant détectée', match_type: 'regex', match_config: { field: 'commentaire_libre', pattern: '(d[ée]j[àa].*(?:eap|formation|étudiant))|(?:ancien.*(?:eap|étudiant))|(?:reviens|retour).*(?:eap|formation)', case_insensitive: true }, points: 20, priority: 10, display_order: 3, is_active: true, is_system: true, disqualification_reason: '' },

  // ── Malus ────────────────────────────────────────────────────────────────
  { key: 'malus_pack_haut_acompte_bas', category: 'malus', label: 'Incohérence pack D/E + acompte < 100K', description: 'Pack premium choisi mais acompte ridicule', match_type: 'pack_acompte_combo', match_config: { pack_tiers: ['D','E'], acompte_threshold: 100000, acompte_compare: '<' }, points: -20, priority: 20, display_order: 1, is_active: true, is_system: true, disqualification_reason: '' },
  { key: 'malus_pack_bas_acompte_haut', category: 'malus', label: 'Incohérence pack A/B + acompte > 1M',   description: 'Pack bas mais acompte énorme — suspect',     match_type: 'pack_acompte_combo', match_config: { pack_tiers: ['A','B'], acompte_threshold: 1000000, acompte_compare: '>' }, points: -20, priority: 10, display_order: 2, is_active: true, is_system: true, disqualification_reason: '' },

  // ── Disqualifications ───────────────────────────────────────────────────
  { key: 'dq_pack_a',        category: 'disqualification', label: 'Pack A < 200K FCFA',           description: 'Sous le minimum',                  match_type: 'pack_tier',     match_config: { tier: 'A' },                       points: 0, priority: 30, display_order: 1, is_active: true, is_system: true, disqualification_reason: 'Pack A — Moins de 200 000 FCFA (sous le minimum)' },
  { key: 'dq_age_below_18',  category: 'disqualification', label: 'Âge < 18 ans',                  description: '',                                  match_type: 'age_below',     match_config: { age_threshold: 18 },              points: 0, priority: 20, display_order: 2, is_active: true, is_system: true, disqualification_reason: 'Âge < 18 ans' },
  { key: 'dq_phone_invalid', category: 'disqualification', label: 'Numéro WhatsApp manquant/invalide', description: 'Moins de 8 chiffres',           match_type: 'phone_invalid', match_config: {},                                  points: 0, priority: 10, display_order: 3, is_active: true, is_system: true, disqualification_reason: 'Numéro WhatsApp manquant ou invalide' },
]
